version: '3'

services:

  gin:
    build: ./gin
    environment:
      KAFKA_BROKER_URL: broker:9092
      USER_TOPIC: streaming.user_activity
      TRANSACTIONS_PER_SECOND: 1000


  vodka:
    build: ./vodka
    environment:
      KAFKA_BROKER_URL: broker:9092
      USER_TOPIC: streaming.user_activity
      TRANSACTIONS_PER_SECOND: 1000
      CONSUMER_AUTO_OFFSET_RESET: 'latest'

networks:
  default:
    external:
      name: kafka-network
