version: '3'

services:

  gin:
    build: ./gin
    environment:
      KAFKA_BROKER_URL: broker:9092
      USER_TOPIC: streaming.user_activity
      TRANSACTIONS_PER_SECOND: 5


  vodka:
    build: ./vodka
    environment:
      KAFKA_BROKER_URL: broker:9092
      USER_TOPIC: streaming.user_activity
      CLEANED_USER_TOPIC: derivedstream.cleaned_user_events

  bourbon:
    build: ./bourbon
    environment:
      KAFKA_BROKER_URL: broker:9092
      USER_TOPIC: streaming.user_activity
      DATAQUALITY_TOPIC: derivedstream.quality_user_activity

networks:
  default:
    external:
      name: kafka-network
